name: Cat-WolfChannelMultiPlugin
version: 1.0
main: me.catwolf.multiplugin.CatWolfChannelMultiPlugin
api-version: '1.21'
commands:
  belohnung:
      description: Holt deine Cat-WolfChannel Belohnung ab.
          usage: /belohnung
          